# Generated by Django 2.2.3 on 2019-07-31 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0003_auto_20190731_1514'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='e',
        ),
        migrations.RemoveField(
            model_name='room',
            name='n',
        ),
        migrations.RemoveField(
            model_name='room',
            name='s',
        ),
        migrations.RemoveField(
            model_name='room',
            name='w',
        ),
        migrations.AddField(
            model_name='room',
            name='e_to',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='room',
            name='n_to',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='room',
            name='s_to',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='room',
            name='w_to',
            field=models.IntegerField(default=0),
        ),
    ]
