# Generated by Django 2.2.3 on 2019-08-01 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0005_auto_20190731_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='items',
            field=models.CharField(default='', max_length=500),
        ),
    ]
