# Generated by Django 2.2.3 on 2019-08-01 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0006_room_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='e',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='room',
            name='n',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='room',
            name='s',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='room',
            name='w',
            field=models.IntegerField(default=-1),
        ),
    ]
